# Generated by Django 4.1.1 on 2022-10-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignment_id_alter_assignmentfilecontent_id_and_more'),
        ('assignment', '0002_submission_checked'),
    ]

    operations = [
    ]
